site_name: "Semantic Llama"
theme:
  name: material
  analytics:
    gtag: G-2SYBSJVZ23
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  - Home: home.md
  - Index: index.md
  - Credits: credits.md
site_url: https://cmungall.github.io/semantic-llama/
repo_url: https://github.com/cmungall/semantic-llama/
